"""add date field to tournament

Revision ID: 80a869847ba4
Revises: c4b4ef7307fc
Create Date: 2021-02-25 20:50:31.527281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a869847ba4'
down_revision = 'c4b4ef7307fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tournament_timestamp'), 'tournament', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_timestamp'), table_name='tournament')
    op.drop_column('tournament', 'timestamp')
    # ### end Alembic commands ###
